# Generated by Django 4.1.6 on 2024-05-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='video',
            field=models.CharField(max_length=200),
        ),
    ]
